//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Web.PronistService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parameters.InvoiceList", Namespace="http://schemas.datacontract.org/2004/07/ProDisplay.Global._Response")]
    [System.SerializableAttribute()]
    public partial class ParametersInvoiceList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid InvoiceGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InvoiceTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode {
            get {
                return this.CustomerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCodeField, value) != true)) {
                    this.CustomerCodeField = value;
                    this.RaisePropertyChanged("CustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid InvoiceGuid {
            get {
                return this.InvoiceGuidField;
            }
            set {
                if ((this.InvoiceGuidField.Equals(value) != true)) {
                    this.InvoiceGuidField = value;
                    this.RaisePropertyChanged("InvoiceGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InvoiceTotal {
            get {
                return this.InvoiceTotalField;
            }
            set {
                if ((this.InvoiceTotalField.Equals(value) != true)) {
                    this.InvoiceTotalField = value;
                    this.RaisePropertyChanged("InvoiceTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceType {
            get {
                return this.InvoiceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceTypeField, value) != true)) {
                    this.InvoiceTypeField = value;
                    this.RaisePropertyChanged("InvoiceType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parameters.InvoiceByte", Namespace="http://schemas.datacontract.org/2004/07/ProDisplay.Global._Response")]
    [System.SerializableAttribute()]
    public partial class ParametersInvoiceByte : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Statu {
            get {
                return this.StatuField;
            }
            set {
                if ((this.StatuField.Equals(value) != true)) {
                    this.StatuField = value;
                    this.RaisePropertyChanged("Statu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PronistService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InvoiceList", ReplyAction="http://tempuri.org/IService/InvoiceListResponse")]
        Nop.Web.PronistService.ParametersInvoiceList[] InvoiceList(string Apikey, string CustomerCode, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InvoiceList", ReplyAction="http://tempuri.org/IService/InvoiceListResponse")]
        System.Threading.Tasks.Task<Nop.Web.PronistService.ParametersInvoiceList[]> InvoiceListAsync(string Apikey, string CustomerCode, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InvoiceByte", ReplyAction="http://tempuri.org/IService/InvoiceByteResponse")]
        Nop.Web.PronistService.ParametersInvoiceByte InvoiceByte(string Apikey, string InvoiceId, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InvoiceByte", ReplyAction="http://tempuri.org/IService/InvoiceByteResponse")]
        System.Threading.Tasks.Task<Nop.Web.PronistService.ParametersInvoiceByte> InvoiceByteAsync(string Apikey, string InvoiceId, string ipAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Nop.Web.PronistService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Nop.Web.PronistService.IService>, Nop.Web.PronistService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Nop.Web.PronistService.ParametersInvoiceList[] InvoiceList(string Apikey, string CustomerCode, string ipAddress) {
            return base.Channel.InvoiceList(Apikey, CustomerCode, ipAddress);
        }
        
        public System.Threading.Tasks.Task<Nop.Web.PronistService.ParametersInvoiceList[]> InvoiceListAsync(string Apikey, string CustomerCode, string ipAddress) {
            return base.Channel.InvoiceListAsync(Apikey, CustomerCode, ipAddress);
        }
        
        public Nop.Web.PronistService.ParametersInvoiceByte InvoiceByte(string Apikey, string InvoiceId, string ipAddress) {
            return base.Channel.InvoiceByte(Apikey, InvoiceId, ipAddress);
        }
        
        public System.Threading.Tasks.Task<Nop.Web.PronistService.ParametersInvoiceByte> InvoiceByteAsync(string Apikey, string InvoiceId, string ipAddress) {
            return base.Channel.InvoiceByteAsync(Apikey, InvoiceId, ipAddress);
        }
    }
}
